package com.cybage.exception;

public class ExceptionDemo {
	public static void Method3()
	{
	try{
	int a=12;
	int b=0;
	int c=a/b;
	System.out.println("OUTPUT"+c);
	}
	catch (NullPointerException e) {
		e.printStackTrace();
	}
	}
	public static void Method2(){
		Method3();
	}
public static void Method1(){
		Method2();
	}
	public static void main(String[] args) {
		Method1();			

	}

}
