package com.cybage.exception;

public class Demo {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		try {
		int a = 10;
		int b = 0;
		int c =a/b;
		System.out.println("c="+c);
		}
		catch (Exception e) {
//			System.out.println(e.getMessage());
			e.printStackTrace();
		}
		System.out.println("After catch block...");
	}

}
